# Generated by Django 5.0.7 on 2024-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='music',
            field=models.ManyToManyField(related_name='artists', to='myapp.music'),
        ),
    ]
