# Generated by Django 5.0.7 on 2024-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_genre_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='music',
            field=models.ManyToManyField(to='myapp.music'),
        ),
    ]
