# Generated by Django 5.0.7 on 2024-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='coverImg',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='profileImg',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
