# Generated by Django 5.0.7 on 2024-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_artist_coverimg_artist_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='img',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
