# Generated by Django 5.0.7 on 2024-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_album_img_music_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
