# Generated by Django 5.0.7 on 2024-07-30 15:41

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_album_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.albums_directory),
        ),
    ]
