# Generated by Django 5.0.7 on 2024-08-01 14:40

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_album_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.music_directory),
        ),
        migrations.AlterField(
            model_name='music',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.music_img_directory),
        ),
    ]
