# Generated by Django 5.0.7 on 2024-08-12 19:21

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to=myapp.models.profileImg_directory)),
                ('coverImg', models.ImageField(blank=True, null=True, upload_to=myapp.models.coverImg_directory)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.albums_directory),
        ),
        migrations.AlterField(
            model_name='artist',
            name='coverImg',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.coverImg_directory),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.profileImg_directory),
        ),
    ]
