# Generated by Django 5.0.7 on 2024-09-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_liked_songs_liked_musics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followed_artists',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='liked_albums',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='liked_musics',
            old_name='user',
            new_name='profile',
        ),
    ]
