# Generated by Django 5.0.7 on 2024-10-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='LM_musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('liked_musics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liked_musics')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.music')),
            ],
        ),
        migrations.RemoveField(
            model_name='liked_musics',
            name='musics',
            field=models.ManyToManyField(through='myapp.LM_musics', to='myapp.music'),
        ),
        migrations.AddField(
            model_name='liked_musics',
            name='musics',
            field=models.ManyToManyField(through='myapp.LM_musics', to='myapp.music'),
        ),
    ]
