# Generated by Django 5.0.7 on 2024-10-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_lm_musics_alter_liked_musics_musics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lm_musics',
            old_name='music',
            new_name='liked_music',
        ),
    ]
