# Generated by Django 5.0.7 on 2024-10-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_music_lm_musics_liked_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lm_musics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FA_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('liked_artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.followed_artists')),
            ],
        ),
        migrations.RemoveField(
            model_name='followed_artists',
            name='artist',
            field=models.ManyToManyField(through='myapp.FA_artist', to='myapp.artist'),
        ),
        migrations.AddField(
            model_name='followed_artists',
            name='artist',
            field=models.ManyToManyField(through='myapp.FA_artist', to='myapp.artist'),
        ),
        migrations.CreateModel(
            name='LA_albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
                ('liked_albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liked_albums')),
            ],
        ),
        migrations.RemoveField(
            model_name='liked_albums',
            name='albums',
            field=models.ManyToManyField(through='myapp.LA_albums', to='myapp.album'),
        ),
         migrations.AddField(
            model_name='liked_albums',
            name='albums',
            field=models.ManyToManyField(through='myapp.LA_albums', to='myapp.album'),
        ),
    ]
