# Generated by Django 5.0.7 on 2024-10-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_lm_musics_created_at_fa_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followed_artists',
            old_name='artist',
            new_name='artists',
        ),
    ]
