# Generated by Django 5.0.7 on 2024-10-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_l_musics_alter_list_musics'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
