# Generated by Django 5.0.7 on 2024-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_music_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.IntegerField(default=0),
        ),
    ]
