# Generated by Django 5.0.7 on 2024-11-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_album_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='L_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.list')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lists', models.ManyToManyField(through='myapp.L_list', to='myapp.list')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='l_list',
            name='liked_lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_lists', to='myapp.liked_lists'),
        ),
    ]
