# Generated by Django 5.0.7 on 2024-11-11 15:31

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_l_list_liked_lists_l_list_liked_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l_list',
            name='liked_lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liked_lists'),
        ),
        migrations.AlterField(
            model_name='music',
            name='img',
            field=models.ImageField(null=True, upload_to=myapp.models.music_img_directory),
        ),
    ]
