# Generated by Django 5.0.7 on 2024-11-11 15:31

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_l_list_liked_lists_alter_music_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.music_img_directory),
        ),
    ]
