# Generated by Django 5.0.7 on 2024-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='myapp.profile'),
        ),
    ]
